// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFOX_ZT5xo1dqej-MFgG3T5zK0Sb1jFhg',
    appId: '1:209076167956:web:f3ef9d8d3bdd4b861a4e01',
    messagingSenderId: '209076167956',
    projectId: 'e-commerce-app-ffa8d',
    authDomain: 'e-commerce-app-ffa8d.firebaseapp.com',
    storageBucket: 'e-commerce-app-ffa8d.appspot.com',
    measurementId: 'G-07W1ZDLEB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3o35zA9LPYj4UO1y4MKX87XSkAxLzZb8',
    appId: '1:209076167956:android:fe8fe395cdac39c31a4e01',
    messagingSenderId: '209076167956',
    projectId: 'e-commerce-app-ffa8d',
    storageBucket: 'e-commerce-app-ffa8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDYTkdJEGOmM_uu9UqkESMcCmLJMY0_04',
    appId: '1:209076167956:ios:a62a9f8e581721ab1a4e01',
    messagingSenderId: '209076167956',
    projectId: 'e-commerce-app-ffa8d',
    storageBucket: 'e-commerce-app-ffa8d.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDYTkdJEGOmM_uu9UqkESMcCmLJMY0_04',
    appId: '1:209076167956:ios:a62a9f8e581721ab1a4e01',
    messagingSenderId: '209076167956',
    projectId: 'e-commerce-app-ffa8d',
    storageBucket: 'e-commerce-app-ffa8d.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFOX_ZT5xo1dqej-MFgG3T5zK0Sb1jFhg',
    appId: '1:209076167956:web:74ffe98f075b1a9b1a4e01',
    messagingSenderId: '209076167956',
    projectId: 'e-commerce-app-ffa8d',
    authDomain: 'e-commerce-app-ffa8d.firebaseapp.com',
    storageBucket: 'e-commerce-app-ffa8d.appspot.com',
    measurementId: 'G-MKH3X2DNJ7',
  );
}
